Support for future post status
jgrossi/corcel pull request #420
Opened 2018-10-29 15:53 UTC by valentinxxx

2018-10-29 16:10 UTC, jgrossi requested changes
hey! thanks for the PR! good call. just a small change 💪🎉

2018-10-29 16:10 UTC, jgrossi commented on src/Model/Builder/PostBuilder.php
> +                $query->where('post_date', '<=', \Carbon\Carbon::now()->format('Y-m-d H:i:s'));
I think this should be `->whereDate()` and just `Carbon::now()`

2018-10-29 16:25 UTC, 0xb4lint commented on src/Model/Builder/PostBuilder.php
> +                $query->where('post_date', '<=', \Carbon\Carbon::now()->format('Y-m-d H:i:s'));
I've changed `\Carbon\Carbon::now()` to `Carbon::now()`.

Please correct me if I'm wrong: as I can see using `whereDate()` generates a `strftime('%Y-%m-%d', "post_date") <= cast(? as text)` query (and using `whereTime()` generates `strftime('%H:%M:%S', "post_date") <= cast(? as text))` query).

So I think `where()` is the proper one in this case.

2018-10-30 09:30 UTC, valentinxxx commented
@jgrossi I've changed `\Carbon\Carbon::now()` to `Carbon::now()`.

Please correct me if I'm wrong: as I can see using `whereDate()` generates a `strftime('%Y-%m-%d', "post_date") <= cast(? as text)` query (and using `whereTime()` generates `strftime('%H:%M:%S', "post_date") <= cast(? as text))` query).

So I think `where()` is the proper one in this case.

2018-11-12 18:04 UTC, jgrossi commented on src/Model/Builder/PostBuilder.php
> +                $query->where('post_date', '<=', \Carbon\Carbon::now()->format('Y-m-d H:i:s'));
you're right! sounds good! thanks for sharing! 🎉🔥

2018-11-12 18:04 UTC, jgrossi commented
@valentinxxx do you need this for `2.6` version? the current version (and branch) is `2.7`. any problem for you? thanks!

2018-11-12 18:23 UTC, 0xb4lint commented
@jgrossi `2.7` version will be fine for me 😉 
Should I create a new PR?

2018-11-12 18:25 UTC, jgrossi approved these changes

2018-11-12 18:26 UTC, jgrossi commented
@valentinxxx no worries. I already changed it to `2.7` and gonna merge now and release a new version in a couple of minutes. thanks!

2018-11-12 18:26 UTC, merged